#!/usr/bin/env bash
./mk-project-page.sh asphault
./mk-project-page.sh atomos
./mk-project-page.sh atomve
./mk-project-page.sh dimension-n
./mk-project-page.sh jsdog
./mk-project-page.sh lost
./mk-project-page.sh node-refserver
./mk-project-page.sh outbrk
./mk-project-page.sh pine
./mk-project-page.sh scroller-builder
./mk-project-page.sh spritefast
./mk-project-page.sh tic-tac-toe
